# Generated by Django 4.0.2 on 2022-02-22 01:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title post')),
                ('slug', models.CharField(max_length=50, verbose_name='Slug')),
                ('description', models.CharField(max_length=110, verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.URLField(verbose_name='Image url')),
                ('status', models.BooleanField(default=True, verbose_name='Status Post')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
